export const en = {
  client: {
    account              : 'Account',
    account_updated      : 'Account Updated',
    active               : 'Active',
    add_course           : 'Add Course',
    add_bootcamp         : 'Add Bootcamp',
    add_feedback         : 'Add Feedback',
    admin                : 'Admin',
    address              : 'Address',
    advanced             : 'advanced',
    analytics            : 'Analytics',
    at_risk              : 'At Risk',
    avatar               : 'Avatar',
    avatar_url           : 'Avatar URL',
    back                 : 'Back',
    browse_bootcamps     : 'Browse Bootcamps',
    beginner             : 'beginner',
    bootcamp             : 'Bootcamp',
    bootcamps            : 'Bootcamps',
    calendar             : 'Calendar',
    career               : 'Career',
    create_course        : 'Create Course',
    continue             : 'Continue',
    course               : 'Course',
    courses              : 'Courses',
    create_account       : 'Create account',
    create_an_account    : 'Create an account',
    description          : 'Description',
    done                 : 'Done',
    duration             : 'Duration',
    email                : 'Email',
    enroll               : 'Enroll',
    featured_bootcamps   : 'Featured Bootcamps',
    fetching_feedbacks   : 'Fetching feedbacks...',
    feedback             : 'Feedback',
    feedbacks            : 'Feedbacks',
    firstname            : 'First Name',
    get_started          : 'Get Started',
    give_rating          : 'Give your rating',
    go_back              : 'Go Back',
    invite_user          : 'Invite User',
    intermediate         : 'intermediate',
    in_progress          : 'In Progress',
    lastname             : 'Last Name',
    league_leaders       : 'League Leaders',
    learners             : 'Learners',
    loading              : 'Loading',
    location             : 'Location',
    location_pending     : 'Location pending',
    log_in               : 'Log In',
    log_in_instead       : 'Log In instead',
    log_in_add_feedback  : 'Log in to add feedback or rate.',
    logging_in           : 'Logging In',
    log_out              : 'Log Out',
    logging_out          : 'Logging Out',
    manage               : 'Manage',
    manage_platform      : 'Manage Platform',
    minimum_skill_       : 'Minimum skill',
    name                 : 'Name',
    new_bootcamp         : 'New Bootcamp',
    no_feedback_bootcamp : 'No feedback yet for this bootcamp.',
    no_records_yet       : 'No records yet.',
    not_set              : 'Not set',
    not_yet_rated        : 'Not yet rated',
    organization         : 'Organization',
    overview             : 'Overview',
    password             : 'Password',
    phone                : 'Phone',
    progress             : 'Progress',
    program_fit          : 'Program Fit',
    quick_actions        : 'Quick Actions',
    rating               : 'Rating',
    refresh              : 'Refresh',
    register             : 'Register',
    remote_or_pending    : 'Remote or location pending',
    retry                : 'Retry',
    review               : 'Review',
    save_setting         : 'Save Setting',
    save_bootcamp        : 'Save Bootcamp',
    scholarship_available: 'Scholarship available',
    search_bootcamps     : 'Search bootcamps',
    setting              : 'Setting',
    sort                 : 'Sort',
    submitting           : 'Submitting',
    target_bootcamp      : 'Target bootcamp',
    typically_starts_from: 'Typically starts from',
    title                : 'Title',
    tuition              : 'Tuition',
    view                 : 'View',
    update_account       : 'Update Account',
    user                 : 'User',
    users                : 'Users',
    username             : 'Username',
    view_all             : 'View All',
    view_students        : 'View Students',
    website              : 'Website',
    worldwide            : 'worldwide.',
    your_courses         : 'Your Courses',

    bootcamp_para        : {
      1                : 'Compare programs, costs, outcomes, and course focus from The CodeCoach Project catalogue.',
      trainer_workspace: 'Trainer workspace',
    },
    filters: {
      bootcamp: {
        rating        : 'Rating',
        averageCost   : 'Cost low to high',
        '-averageCost': 'Cost high to low',
        name          : 'Name',
      },
    },
    meta     : {
      full_stack_development: 'High demand pathway with broad hiring coverage',
      mobile_app_development: 'Strong fit for product teams and startup work',
      cloud_devops          : 'Practical infrastructure and deployment skills'
    },
    days     : {
      mon: 'Mon',
      tue: 'Tue',
      wed: 'Wed',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
      sun: 'Sun'
    },
    dashboard: {
      across_all_courses                 : 'across all courses',
      active_courses                     : 'Active Courses',
      average_progress_day               : 'Average class progress by day.',
      average_rating                     : 'Average rating',
      average_speed                      : 'Average Speed',
      browse_bootcamps                   : 'Browse Bootcamps',
      browse_courses                     : 'Browse Courses',
      catalogue_interest                 : 'Catalogue Interest',
      completion_rate                    : 'Completion Rate',
      courses_active                     : '{course}, active',
      courses_completed                  : 'Courses Completed',
      days_row                           : 'days in a row',
      engagement_trend_week              : 'Engagement trend across the week.',
      featured_bootcamps                 : 'Featured Bootcamps',
      featured_course_title_user         : 'Featured Bootcamps',
      featured_course_description_user   : 'Discover top-rated bootcamps aligned with your next move.',
      featured_course_title_trainer      : 'Popular Bootcamps',
      featured_course_description_trainer: 'See what learners are choosing across the catalogue.',
      keep_it_up                         : 'Keep it up',
      last_cohort                        : 'Last Cohort',
      learner_mix                        : 'Learner Mix',
      learning_progress                  : 'Learning Progress',
      no_course_active                   : 'No course active',
      of_target_pace                     : 'of target pace',
      out_of_max_rate                    : 'out of 5.0',
      opportunities                      : 'Opportunities',
      operational_focus                  : 'Operational Focus',
      platform_watchlist                 : 'Platform Watchlist',
      published_now                      : 'published now',
      recent_feedback                    : 'Recent Feedback',
      recent_feedbacks                   : 'Recent Feedbacks',
      recommendation_title               : 'Recommendations',
      recommendations_title_user         : 'Recommendations For You',
      recommendation_message_user        : 'Based on your interests and learning goals.',
      similar_bootcamps_in_market        : '{index} similar bootcamps in market',
      study_streak                       : 'Study Streak',
      total_students                     : 'Total Students',
      view_profile                       : 'View Profile',
      weekly_activity                    : 'Weekly Activity',
      welcome_back                       : 'Welcome back',
      welcome_message_user               : 'Continue your learning journey and explore new bootcamps.',
      welcome_message_trainer            : 'Manage your bootcamps, courses and track student progress.',
      welcome_message_admin              : 'Monitor the platform, active programs, and catalogue health.',
      your_current_bootcamp              : 'Your current bootcamp',
      your_bootcamp                      : 'Your bootcamp',
      your_bootcamps                     : 'Your bootcamps',
      your_current_courses               : 'Your Current Courses'
    },
    career_options: {
      web_development           : 'Web Development',
      mobile_development        : 'Mobile Development',
      ui_ux                     : 'UI/UX',
      data_science              : 'Data Science',
      data_security             : 'Data Security',
      software_engineering      : 'Software Engineering',
      full_stack_web_development: 'Full Stack Web Development',
      dev_ops                   : 'Dev Ops',
      ai                        : 'AI',
      machine_learning          : 'Machine Learning',
      cloud_computing           : 'Cloud Computing',
      cyber_security            : 'Cyber Security',
      other                     : 'Other',
    },
    minimum_skill: {
      beginner    : 'beginner',
      intermediate: 'intermediate',
      advanced    : 'advanced',
    },
    traits: {
      housing         : 'Housing',
      job_assistance  : 'Job assistance',
      job_guarantee   : 'Job guarantee',
      gi_bill_accepted: 'GI bill accepted',
    },
    roles: {
      user   : 'Student',
      trainer: 'Trainer',
      admin  : 'Admin',
      guest  : 'Guest',
    },
    success: {
      bootcamp_created: 'Bootcamp Created',
      course_added    : 'Course added',
      user_created    : 'User created',
      user_deleted    : 'User deleted',
      user_updated    : 'User updated',
      user_registered : 'User registered',
      user_logged_in  : 'User logged in',
    },
    error: {
      bootcamp_required             : 'Create or open a bootcamp before adding courses.',
      failed_find                   : 'Failed to find the requested document',
      failed_link_route             : '[mainRoute]: Failed to link Route: {linker}',
      failed_update                 : 'Failed to update this document',
      generic                       : 'Something went wrong while loading this page.',
      invalid_data_response         : 'Invalid data response',
      league_full                   : 'League is full',
      league_sched_before_invite    : 'League schedule must be set before inviting',
      membership_already_processed  : 'Membership already processed',
      max_count_per_myleague        : 'Max {count} teams per myleague',
      missing_or_invalid_api_version: 'Missing or Invalid api version',
      no_id                         : 'No id or invalid id provided',
      not_found                     : `NOT FOUND: {field} not found`,
      unable_load_page              : 'Unable to load this page',
      unable_create_account         : 'Unable to create account',
      unable_create_course          : 'Unable to create course',
      unable_create_bootcamp        : 'Unable to create bootcamp',
      unable_log_in                 : 'Unable to log in',
      user_not_authenticated        : 'User not authenticated',
      user_not_authorized           : 'User not authorized',
      user_not_found                : 'User not found',
      user_has_team                 : 'User already has a team',
      user_select_team_required     : 'All members must select a team before drafting',
      team_has_already_selected     : '{field} has already been selected',
      team_already_selected         : 'Team already selected',
    },
    message: {
      draft_started              : 'Draft date has already started',
      footer                     : 'Learn faster with curated technical bootcamps and modern developer education, ',
      membership_expired         : 'Membership expired',
      membership_processed       : 'Membership already processed',
      newly_created_bootcamp     : 'newly created bootcamp will appear here',
      no_courses_published_yet   : 'No courses published yet.',
      owner_no_myleague          : 'No MyLeague created',
      find_bootcamp              : 'Find the right bootcamp',
      welcome                    : 'Welcome',
      welcome_description_student: 'Continue your learning journey and explore new bootcamps',
      welcome_description_trainer: 'Manage your bootcamps, courses and track student progress'
    },
    nav: {
      dashboard: 'Dashboard',
      bootcamp : 'Bootcamp',
      bootcamps: 'Bootcamps',
      users    : 'Users',
      user     : {
        user   : 'user',
        account: 'Account',
        manage : 'Manage',
        setting: 'Setting',
        log_out: 'Log Out',
      },
      footer: {
        docs                  : 'Docs',
        api                   : 'API',
        careers               : 'Careers',
        privacy               : 'Privacy',
        all_system_operational: 'All systems operational',
      },
      sidebar: {
        dashboard: 'Dashboard',
      },
    },
    validation: {
      default: {
        invalid   : 'Invalid {field}',
        length    : '{field} length ({value}) must be between {min} and {max} characters',
        min_length: '{field} length ({value}) must be at least {min} characters',
        max_length: '{field} length ({value}) exceeds the limit of characters',
        required  : '{field} is required',
        unique    : '{field} already exists',
      },
      max_league_allowed_user: 'Max limit ({max}) allowed for leagues owned reached ',
      password               : 'Password must be 8+ characters with at least one uppercase, lowercase, number, and symbol.',
    },
  },
  server: {
    response: {
      exists  : '{entity} already exists',
      db_saved: 'new {entity} has been saved to the database',
      success : {
        status_200          : 'OK: Request fetched',
        status_201          : 'CREATED: Request created',
        status_204          : 'NO CONTENT: The server successfully processed the request but there is no content to send in the response.',
        photo_uploaded      : 'OK: Photo Uploaded',
        badge_uploaded      : 'OK: Badge Uploaded',
        avatar_uploaded     : 'OK: Avatar Uploaded',
        courses_deleted     : 'Courses being deleted from bootcamp ID: {id}. Reload page to see the effect',
        collection_seed     : ' MOCK MIGRATION SUCCESSFUL ',
        collection_destroyed: ' COLLECTION/s DESTROYED ',
        logout              : 'User logged out',
        updated             : 'Entity updated',
        deleted             : 'Entity deleted',
        deleted_account     : 'Your account has been deleted.',
        email_sent          : 'Email sent',
        nodemailer_message  : ' Message sent: %s ',
      },
      error: {
        status_400                : 'BAD REQUEST: Client request is Invalid',
        status_401                : 'UNAUTHORIZED: Request cannot be granted unless Client is Authenticated',
        status_403                : 'FORBIDDEN: Necessary permissions is required to access the Requested Resource',
        status_404                : 'NOT FOUND: Resource requested cannot be found',
        status_422                : 'UNPROCESSABLE ENTITY: The data submitted in a form is in the wrong format or is missing required fields',
        status_429                : 'REQUEST OVERLOAD: Throttling limit exceeded for an API',
        status_500                : 'INTERNAL SERVER ERROR: Server encountered an Unhandled Exception',
        status_503                : 'SERVICE UNAVAILABLE: The server is temporarily unable to handle the Request',
        status_504                : 'GATEWAY TIMEOUT: The server acting as a gateway did not receive a timely response from an upstream server',
        account_deleted           : 'Account has been deleted',
        account_scheduled_delete  : 'Account is already scheduled for deletion.',
        cors_not_allowed          : 'CORS ERROR: Not allowed by Access-Control-Allow-Origin',
        entity_exists             : 'Entity already exists',
        invalid_start_date        : 'Please select a valid start date',
        invalid_start_date_past   : 'Start date cannot be in the past',
        is_required               : '{field} is required.',
        org_required              : 'Organization is required for Admin',
        already_exists            : '{entity} already exists',
        one_feedback              : 'Only one feedback per user is allowed',
        not_enrolled_course       : 'You are not enrolled in this course',
        not_found_top_bootcamps   : 'Top bootcamps not found',
        not_found_bootcamp        : 'Bootcamp not found with id of {id}',
        not_found_course          : 'Course not found with id of {id}',
        not_found_enrollment      : 'Enrollment not found with id of {id}',
        not_found_feedback        : 'No feedback found with the id {id}',
        not_found                 : 'There is no user with id {id}',
        bootcamp_already_published: 'The user with ID {id} has already published a bootcamp',
        failed_upload             : ' Please upload a file ',
        failed_upload_avatar      : ' Please upload an avatar ',
        failed_filesize           : 'File size cannot exceed {fileSize}',
        failed_seed               : ' FAILED TO SEED COLLECTION/s SEED ',
        failed_destroy            : ' FAILED TO DESTROY COLLECTION/s ',
        failed_delete             : ' FAILED TO DELETE ENTITY ',
        failed_delete_account     : ' Failed to delete your account ',
        failed_find               : ' FAILED TO FIND ENTITY ',
        failed_create             : ' FAILED TO CREATE ENTITY ',
        failed_update             : ' FAILED TO UPDATE ENTITY ',
        failed_register           : ' FAILED TO REGISTER ',
        failed_login              : ' FAILED TO LOGIN ',
        failed_logout             : ' FAILED TO LOGOUT ',
        invalid_credential        : 'Please provide a valid email and password',
        invalid_password          : 'Invalid password',
        invalid_token             : 'Invalid token',
        nodemailer_message        : ' Error occurred: %s ',
        not_student               : 'User {user} is not a student',
        not_owner                 : 'User {user} is unauthorized to update course {entity}',
        role_not_allowed          : 'Current role {role} is unauthorized to access this route',
        parse_err                 : 'Error parsing JSON: {error}',
        not_instance              : 'This class cannot be instantiated',
        session_expired           : 'Session has expired',
        static_class              : 'This is a static class',
        failed_email              : 'Email could not be sent',
        reset_subject             : 'Password Reset Request',
        reset_message             : 'A request has been made to reset your password. If you made this request, please copy the following code into the prompt in: \n\n {resetUrl} to verify your identity.',
      },
    },
    schema: {
      name                  : 'Please add a bootcamp name/title',
      max_length_name       : 'Name can not be more than 50 characters',
      description           : 'Please add a description',
      min_length_description: 'Description can not be less than 20 characters',
      max_length_description: 'Description can not be more than 250 characters',
      url                   : 'Please use a valid URL with HTTP or HTTPS',
      max_length_phone      : 'Phone number can not be longer than 20 characters',
      email                 : 'Please add a valid email',
      address               : 'Please add an address',
      duration              : 'Please add a duration',
      average_rating_min    : 'Rating must be at least 1',
      average_rating_max    : 'Rating must can not be more than 10',
      careers               : 'Please add one or more careers',
      course_title          : 'Please add a course title',
      course_week           : 'Please add number of weeks',
      course_tuition        : 'Please add a tuition cost',
      minimum_skill         : 'Please add a minimum skill',
      feedback_title        : 'Please add a title to your Feedback',
      feedback_rating       : 'Please rating is required',
      first_name            : 'Please provide your first name',
      last_name             : 'Please provide your family/last name',
      password              : 'Please add a password',
    },
    success: {
      ok     : 'OK: Request fetched',
      created: 'CREATED: Request created',
      updated: 'Entity updated',
      deleted: 'Entity deleted',
      logout : 'User logged out',
    },
    error: {
      bad_request       : 'Client request is invalid.',
      unauthorized      : 'You must be authenticated to access this resource.',
      forbidden         : 'You do not have permission to access this resource.',
      not_found         : 'Resource not found.',
      route_not_found   : 'Route not found: {path}',
      validation_failed : 'Validation failed.',
      account_deleted   : 'Account has been deleted.',
      session_expired   : 'Session has expired.',
      invalid_credential: 'Please provide a valid email and password.',
      already_exists    : '{entity} already exists.',
      role_not_allowed  : 'Current role {role} is unauthorized to access this route.',
      required          : '{field} is required.',
    },
  },
} as const
