export const es = {
  "client": {
    "account": "Cuenta",
    "account_updated": "Cuenta actualizada",
    "active": "Activa",
    "add_course": "Agregar curso",
    "add_bootcamp": "Agregar campo de entrenamiento",
    "add_feedback": "Agregar comentarios",
    "admin": "Administradora",
    "address": "DIRECCIÓN",
    "advanced": "avanzada",
    "analytics": "Analítica",
    "at_risk": "En riesgo",
    "avatar": "Avatar",
    "avatar_url": "Avatar URL",
    "back": "Atrás",
    "browse_bootcamps": "Explorar campamentos de entrenamiento",
    "beginner": "principiante",
    "bootcamp": "Campamento de entrenamiento",
    "bootcamps": "Campamentos de entrenamiento",
    "calendar": "Calendario",
    "career": "Carrera",
    "create_course": "Crear curso",
    "continue": "Continuar",
    "course": "Curso",
    "courses": "Cursos",
    "create_account": "Crear una cuenta",
    "create_an_account": "Crear una cuenta",
    "description": "Descripción",
    "done": "Hecho",
    "duration": "Duración",
    "email": "Correo electrónico",
    "enroll": "Inscribirse",
    "featured_bootcamps": "Campamentos de entrenamiento destacados",
    "fetching_feedbacks": "Recuperando comentarios...",
    "feedback": "Comentario",
    "feedbacks": "Comentarios",
    "firstname": "Nombre de pila",
    "get_started": "Empezar",
    "give_rating": "da tu calificación",
    "go_back": "Volver",
    "invite_user": "Invitar usuario",
    "intermediate": "intermedia",
    "in_progress": "En curso",
    "lastname": "Apellido",
    "league_leaders": "Líderes de la liga",
    "learners": "Estudiantes",
    "loading": "Cargando",
    "location": "Ubicación",
    "location_pending": "Ubicación pendiente",
    "log_in": "Acceso",
    "log_in_instead": "Inicie sesión en su lugar",
    "log_in_add_feedback": "Inicie sesión para agregar comentarios o calificar.",
    "logging_in": "Iniciar sesión",
    "log_out": "Finalizar la sesión",
    "logging_out": "Cerrar sesión",
    "manage": "Administrar",
    "manage_platform": "Administrar plataforma",
    "minimum_skill_": "Habilidad mínima",
    "name": "Nombre",
    "new_bootcamp": "Nuevo campo de entrenamiento",
    "no_feedback_bootcamp": "Aún no hay comentarios sobre este bootcamp.",
    "no_records_yet": "Aún no hay registros.",
    "not_set": "No establecido",
    "not_yet_rated": "Aún no calificado",
    "organization": "Organización",
    "overview": "Descripción general",
    "password": "Contraseña",
    "phone": "Teléfono",
    "progress": "Progreso",
    "program_fit": "Ajuste del programa",
    "quick_actions": "Acciones Rápidas",
    "rating": "Clasificación",
    "refresh": "Refrescar",
    "register": "Registro",
    "remote_or_pending": "Remota o ubicación pendiente",
    "retry": "Rever",
    "review": "Revisar",
    "save_setting": "Guardar configuración",
    "save_bootcamp": "Guardar campo de entrenamiento",
    "scholarship_available": "Beca disponible",
    "search_bootcamps": "Buscar campamentos de entrenamiento",
    "setting": "Configuración",
    "sort": "Clasificar",
    "submitting": "Sumisión",
    "target_bootcamp": "Campamento de entrenamiento objetivo",
    "typically_starts_from": "Normalmente comienza desde",
    "title": "Título",
    "tuition": "Matrícula",
    "view": "Vista",
    "update_account": "Actualizar cuenta",
    "user": "Usuaria",
    "users": "Usuarias",
    "username": "Nombre de usuario",
    "view_all": "Ver todo",
    "view_students": "Ver estudiantes",
    "website": "Sitio web",
    "worldwide": "mundial.",
    "your_courses": "Tus cursos",
    "bootcamp_para": {
      "1": "Compare programas, costos, resultados y enfoque de cursos del catálogo del Proyecto CodeCoach.",
      "trainer_workspace": "Espacio de trabajo del formador"
    },
    "filters": {
      "bootcamp": {
        "rating": "Clasificación",
        "averageCost": "Costo de menor a mayor",
        "-averageCost": "Costo de alto a bajo",
        "name": "Nombre"
      }
    },
    "meta": {
      "full_stack_development": "Ruta de alta demanda con amplia cobertura de contratación",
      "mobile_app_development": "Fuerte ajuste para equipos de productos y trabajos de startups",
      "cloud_devops": "Habilidades prácticas de infraestructura y implementación."
    },
    "days": {
      "mon": "Lun",
      "tue": "Mar",
      "wed": "Casarse",
      "thu": "Jue",
      "fri": "Vie",
      "sat": "Se sentó",
      "sun": "Sol"
    },
    "dashboard": {
      "across_all_courses": "en todos los cursos",
      "active_courses": "Cursos activos",
      "average_progress_day": "Progreso promedio de clase por día.",
      "average_rating": "Calificación promedio",
      "average_speed": "Velocidad promedio",
      "browse_bootcamps": "Explorar campamentos de entrenamiento",
      "browse_courses": "Explorar cursos",
      "catalogue_interest": "Interés del catálogo",
      "completion_rate": "Tasa de finalización",
      "courses_active": "{course}, activa",
      "courses_completed": "Cursos completados",
      "days_row": "días seguidos",
      "engagement_trend_week": "Tendencia de participación a lo largo de la semana.",
      "featured_bootcamps": "Campamentos de entrenamiento destacados",
      "featured_course_title_user": "Campamentos de entrenamiento destacados",
      "featured_course_description_user": "Descubra los bootcamps mejor valorados alineados con su próximo paso.",
      "featured_course_title_trainer": "Campamentos de entrenamiento populares",
      "featured_course_description_trainer": "Vea lo que los estudiantes eligen en todo el catálogo.",
      "keep_it_up": "Avanza",
      "last_cohort": "Última cohorte",
      "learner_mix": "Mezcla de estudiantes",
      "learning_progress": "Progreso del aprendizaje",
      "no_course_active": "Ningún curso activo",
      "of_target_pace": "del ritmo objetivo",
      "out_of_max_rate": "de 5.0",
      "opportunities": "Oportunidades",
      "operational_focus": "Enfoque operativo",
      "platform_watchlist": "Lista de seguimiento de plataformas",
      "published_now": "publicado ahora",
      "recent_feedback": "Comentarios recientes",
      "recent_feedbacks": "Comentarios recientes",
      "recommendation_title": "Recomendaciones",
      "recommendations_title_user": "Recomendaciones para ti",
      "recommendation_message_user": "Según tus intereses y objetivos de aprendizaje.",
      "similar_bootcamps_in_market": "{index} bootcamps similares en el mercado",
      "study_streak": "Racha de estudios",
      "total_students": "Total de estudiantes",
      "view_profile": "Ver perfil",
      "weekly_activity": "Actividad semanal",
      "welcome_back": "Bienvenido de nuevo",
      "welcome_message_user": "Continúe su viaje de aprendizaje y explore nuevos bootcamps.",
      "welcome_message_trainer": "Administre sus bootcamps, cursos y realice un seguimiento del progreso de los estudiantes.",
      "welcome_message_admin": "Supervise la plataforma, los programas activos y el estado del catálogo.",
      "your_current_bootcamp": "Tu campamento de entrenamiento actual",
      "your_bootcamp": "Tu campamento de entrenamiento",
      "your_bootcamps": "Tus campamentos de entrenamiento",
      "your_current_courses": "Tus cursos actuales"
    },
    "career_options": {
      "web_development": "Desarrollo Web",
      "mobile_development": "Desarrollo Móvil",
      "ui_ux": "UI/UX",
      "data_science": "Ciencia de datos",
      "data_security": "Seguridad de datos",
      "software_engineering": "Ingeniería de software",
      "full_stack_web_development": "Desarrollo web de pila completa",
      "dev_ops": "Operaciones de desarrollo",
      "ai": "AI",
      "machine_learning": "Aprendizaje automático",
      "cloud_computing": "Computación en la nube",
      "cyber_security": "Seguridad cibernética",
      "other": "Otra"
    },
    "minimum_skill": {
      "beginner": "principiante",
      "intermediate": "intermedia",
      "advanced": "avanzada"
    },
    "traits": {
      "housing": "Alojamiento",
      "job_assistance": "Asistencia laboral",
      "job_guarantee": "Garantía de empleo",
      "gi_bill_accepted": "Se acepta el proyecto de ley GI"
    },
    "roles": {
      "user": "Alumna",
      "trainer": "Entrenadora",
      "admin": "Administradora",
      "guest": "Invitada"
    },
    "success": {
      "bootcamp_created": "Campamento de entrenamiento creado",
      "course_added": "Curso agregado",
      "user_created": "Usuario creada",
      "user_deleted": "Usuario eliminada",
      "user_updated": "Usuario actualizada",
      "user_registered": "Usuario registrada",
      "user_logged_in": "Usuario registrado"
    },
    "error": {
      "bootcamp_required": "Cree o abra un bootcamp antes de agregar cursos.",
      "failed_find": "No se pudo encontrar el documento solicitado",
      "failed_link_route": "[mainRoute]: No se pudo vincular la ruta: {linker}",
      "failed_update": "No se pudo actualizar este documento",
      "generic": "Algo salió mal al cargar esta página.",
      "invalid_data_response": "Respuesta de datos no válida",
      "league_full": "la liga esta llena",
      "league_sched_before_invite": "Se debe fijar el calendario de la liga antes de invitar",
      "membership_already_processed": "Membresía ya procesada",
      "max_count_per_myleague": "Máximo de {count} equipos por myleague",
      "missing_or_invalid_api_version": "Versión de API faltante o no válida",
      "no_id": "No se ha proporcionado ninguna identificación o ésta no es válida",
      "not_found": "NO ENCONTRADO: {field} no encontrado",
      "unable_load_page": "No se puede cargar esta página",
      "unable_create_account": "No se puede crear la cuenta",
      "unable_create_course": "No se puede crear el curso",
      "unable_create_bootcamp": "No se puede crear el bootcamp",
      "unable_log_in": "No se puede iniciar sesión",
      "user_not_authenticated": "Usuario no autenticada",
      "user_not_authorized": "Usuario no autorizada",
      "user_not_found": "Usuario no encontrado",
      "user_has_team": "La usuario ya tiene un equipo",
      "user_select_team_required": "Todos los miembros deben seleccionar un equipo antes de redactar",
      "team_has_already_selected": "{field} ya ha sido seleccionado",
      "team_already_selected": "Equipo ya seleccionado"
    },
    "message": {
      "draft_started": "La fecha del draft ya comenzó",
      "footer": "Aprenda más rápido con bootcamps técnicos seleccionados y educación moderna para desarrolladores.",
      "membership_expired": "Membresía caducada",
      "membership_processed": "Membresía ya procesada",
      "newly_created_bootcamp": "El bootcamp recién creado aparecerá aquí.",
      "no_courses_published_yet": "Aún no hay cursos publicados.",
      "owner_no_myleague": "No se ha creado ninguna MyLeague",
      "find_bootcamp": "Encuentra el bootcamp adecuado",
      "welcome": "Bienvenida",
      "welcome_description_student": "Continúe su viaje de aprendizaje y explore nuevos bootcamps",
      "welcome_description_trainer": "Administre sus bootcamps, cursos y realice un seguimiento del progreso de los estudiantes"
    },
    "nav": {
      "dashboard": "Panel",
      "bootcamp": "Campamento de entrenamiento",
      "bootcamps": "Campamentos de entrenamiento",
      "users": "Usuarias",
      "user": {
        "user": "usuaria",
        "account": "Cuenta",
        "manage": "Administrar",
        "setting": "Configuración",
        "log_out": "Finalizar la sesión"
      },
      "footer": {
        "docs": "Documentos",
        "api": "API",
        "careers": "Carreras",
        "privacy": "Privacidad",
        "all_system_operational": "Todos los sistemas operativos."
      },
      "sidebar": {
        "dashboard": "Panel"
      }
    },
    "validation": {
      "default": {
        "invalid": "Inválida {field}",
        "length": "La longitud de {field} ({value}) debe estar entre {min} y {max} caracteres",
        "min_length": "La longitud de {field} ({value}) debe tener al menos {min} caracteres",
        "max_length": "{field} longitud ({value}) excede el límite de caracteres",
        "required": "{field} es obligatorio",
        "unique": "{field} ya existe"
      },
      "max_league_allowed_user": "Se alcanzó el límite máximo ({max}) permitido para las ligas de propiedad.",
      "password": "La contraseña debe tener más de 8 caracteres con al menos una mayúscula, una minúscula, un número y un símbolo."
    }
  },
  "server": {
    "response": {
      "exists": "{entity} ya existe",
      "db_saved": "El nuevo {entity} se ha guardado en la base de datos.",
      "success": {
        "status_200": "OK: Solicitud recuperada",
        "status_201": "CREADO: Solicitud creada",
        "status_204": "SIN CONTENIDO: El servidor procesó exitosamente la solicitud pero no hay contenido para enviar en la respuesta.",
        "photo_uploaded": "OK: foto cargada",
        "badge_uploaded": "OK: Insignia cargada",
        "avatar_uploaded": "OK: Avatar subido",
        "courses_deleted": "Cursos que se eliminan del ID del bootcamp: {id}. Vuelva a cargar la página para ver el efecto.",
        "collection_seed": "MIGRACIÓN SIMULADA EXITOSA",
        "collection_destroyed": "COLECCIÓN/es DESTRUIDAS",
        "logout": "Usuario desconectada",
        "updated": "Entidad actualizada",
        "deleted": "Entidad eliminada",
        "deleted_account": "Tu cuenta ha sido eliminada.",
        "email_sent": "Correo electrónico enviado",
        "nodemailer_message": "Mensaje enviado: %s"
      },
      "error": {
        "status_400": "MALA SOLICITUD: La solicitud del cliente no es válida",
        "status_401": "NO AUTORIZADO: La solicitud no se puede otorgar a menos que el Cliente esté autenticado",
        "status_403": "PROHIBIDO: Se requieren los permisos necesarios para acceder al Recurso Solicitado",
        "status_404": "NO ENCONTRADO: No se puede encontrar el recurso solicitado",
        "status_422": "ENTIDAD NO PROCESABLE: Los datos enviados en un formulario tienen el formato incorrecto o faltan campos obligatorios",
        "status_429": "SOBRECARGA DE SOLICITUD: Se superó el límite de limitación para una API",
        "status_500": "ERROR DEL SERVIDOR INTERNO: El servidor encontró una excepción no controlada",
        "status_503": "SERVICIO NO DISPONIBLE: El servidor no puede manejar temporalmente la Solicitud",
        "status_504": "TIEMPO DE ESPERA DE LA PUERTA DE ENTRADA: El servidor que actúa como puerta de enlace no recibió una respuesta oportuna de un servidor ascendente",
        "account_deleted": "La cuenta ha sido eliminada.",
        "account_scheduled_delete": "La cuenta ya está programada para su eliminación.",
        "cors_not_allowed": "ERROR DE CORS: No permitido por Access-Control-Allow-Origin",
        "entity_exists": "La entidad ya existe.",
        "invalid_start_date": "Por favor seleccione una fecha de inicio válida",
        "invalid_start_date_past": "La fecha de inicio no puede ser en el pasado.",
        "is_required": "Se requiere {field}.",
        "org_required": "Se requiere organización para el administrador",
        "already_exists": "{entity} ya existe",
        "one_feedback": "Sólo se permite un comentario por usuario",
        "not_enrolled_course": "No estás inscrito en este curso.",
        "not_found_top_bootcamps": "Mejores bootcamps no encontrados",
        "not_found_bootcamp": "Bootcamp no encontrado con ID de {id}",
        "not_found_course": "Curso no encontrado con id de {id}",
        "not_found_enrollment": "Inscripción no encontrada con ID de {id}",
        "not_found_feedback": "No se encontraron comentarios con el ID {id}",
        "not_found": "No hay ningún usuario con id {id}",
        "bootcamp_already_published": "El usuario con ID {id} ya publicó un bootcamp",
        "failed_upload": "Por favor sube un archivo",
        "failed_upload_avatar": "Por favor sube un avatar",
        "failed_filesize": "El tamaño del archivo no puede exceder {fileSize}",
        "failed_seed": "FALLO EN LA RECOLECCIÓN DE SEMILLAS SEMILLAS",
        "failed_destroy": "NO SE PUDIÓ DESTRUIR LA/S COLECCIÓN/es",
        "failed_delete": "FALLO AL ELIMINAR LA ENTIDAD",
        "failed_delete_account": "No se pudo eliminar tu cuenta",
        "failed_find": "NO SE PUDO ENCONTRAR LA ENTIDAD",
        "failed_create": "NO SE PUDO CREAR LA ENTIDAD",
        "failed_update": "ERROR AL ACTUALIZAR LA ENTIDAD",
        "failed_register": "NO SE PUDO REGISTRAR",
        "failed_login": "FALLÓ AL INICIAR SESIÓN",
        "failed_logout": "FALLÓ AL CERRAR SESIÓN",
        "invalid_credential": "Por favor proporcione un correo electrónico y una contraseña válidos",
        "invalid_password": "Contraseña no válida",
        "invalid_token": "Token no válido",
        "nodemailer_message": "Se produjo un error: %s",
        "not_student": "La usuario {user} no es una estudiante",
        "not_owner": "El usuario {user} no está autorizado a actualizar el curso {entity}",
        "role_not_allowed": "El rol actual {role} no está autorizado a acceder a esta ruta",
        "parse_err": "Error al analizar JSON: {error}",
        "not_instance": "No se puede crear una instancia de esta clase.",
        "session_expired": "La sesión ha expirado",
        "static_class": "Esta es una clase estática",
        "failed_email": "No se pudo enviar el correo electrónico",
        "reset_subject": "Solicitud de restablecimiento de contraseña",
        "reset_message": "Se ha realizado una solicitud para restablecer su contraseña. Si realizó esta solicitud, copie el siguiente código en el mensaje en: \n\n{resetUrl} para verificar su identidad."
      }
    },
    "schema": {
      "name": "Por favor agregue un nombre/título del bootcamp",
      "max_length_name": "El nombre no puede tener más de 50 caracteres.",
      "description": "Por favor agregue una descripción",
      "min_length_description": "La descripción no puede tener menos de 20 caracteres.",
      "max_length_description": "La descripción no puede tener más de 250 caracteres.",
      "url": "Utilice una URL válida con HTTP o HTTPS",
      "max_length_phone": "El número de teléfono no puede tener más de 20 caracteres.",
      "email": "Por favor agregue un correo electrónico válido",
      "address": "Por favor agregue una dirección",
      "duration": "Por favor agregue una duración",
      "average_rating_min": "La calificación debe ser al menos 1",
      "average_rating_max": "La puntuación no debe ser superior a 10.",
      "careers": "Por favor agregue una o más carreras",
      "course_title": "Por favor agregue un título del curso",
      "course_week": "Por favor agregue el número de semanas",
      "course_tuition": "Por favor agregue un costo de matrícula",
      "minimum_skill": "Por favor agregue una habilidad mínima",
      "feedback_title": "Por favor agregue un título a sus comentarios",
      "feedback_rating": "Por favor se requiere calificación",
      "first_name": "Por favor proporcione su nombre",
      "last_name": "Por favor proporcione su familia/apellido",
      "password": "Por favor agregue una contraseña"
    },
    "success": {
      "ok": "OK: Solicitud recuperada",
      "created": "CREADO: Solicitud creada",
      "updated": "Entidad actualizada",
      "deleted": "Entidad eliminada",
      "logout": "Usuario desconectada"
    },
    "error": {
      "bad_request": "La solicitud del cliente no es válida.",
      "unauthorized": "Debe estar autenticado para acceder a este recurso.",
      "forbidden": "No tienes permiso para acceder a este recurso.",
      "not_found": "Recurso no encontrado.",
      "route_not_found": "Ruta no encontrada: {path}",
      "validation_failed": "La validación falló.",
      "account_deleted": "La cuenta ha sido eliminada.",
      "session_expired": "La sesión ha caducado.",
      "invalid_credential": "Proporcione un correo electrónico y una contraseña válidos.",
      "already_exists": "{entity} ya existe.",
      "role_not_allowed": "El rol actual {role} no está autorizado a acceder a esta ruta.",
      "required": "Se requiere {field}."
    }
  }
} as const
