export const es = {
  "client": {},
  "server": {
    "response": {
      "exists": "{entity} ya existe",
      "db_saved": "El nuevo {entity} se ha guardado en la base de datos.",
      "success": {
        "status_200": "OK: Solicitud recuperada",
        "status_201": "CREADO: Solicitud creada",
        "status_204": "SIN CONTENIDO: El servidor procesó exitosamente la solicitud pero no hay contenido para enviar en la respuesta.",
        "photo_uploaded": "OK: foto cargada",
        "badge_uploaded": "OK: Insignia cargada",
        "avatar_uploaded": "OK: Avatar subido",
        "courses_deleted": "Cursos que se eliminan del ID del bootcamp: {id}. Vuelva a cargar la página para ver el efecto.",
        "collection_seed": "MIGRACIÓN SIMULADA EXITOSA",
        "collection_destroyed": "COLECCIÓN/es DESTRUIDAS",
        "logout": "Usuario desconectada",
        "updated": "Entidad actualizada",
        "deleted": "Entidad eliminada",
        "deleted_account": "Tu cuenta ha sido eliminada.",
        "email_sent": "Correo electrónico enviado",
        "nodemailer_message": "Mensaje enviado: %s"
      },
      "error": {
        "status_400": "MALA SOLICITUD: La solicitud del cliente no es válida",
        "status_401": "NO AUTORIZADO: La solicitud no se puede otorgar a menos que el Cliente esté autenticado",
        "status_403": "PROHIBIDO: Se requieren los permisos necesarios para acceder al Recurso Solicitado",
        "status_404": "NO ENCONTRADO: No se puede encontrar el recurso solicitado",
        "status_422": "ENTIDAD NO PROCESABLE: Los datos enviados en un formulario tienen el formato incorrecto o faltan campos obligatorios",
        "status_429": "SOBRECARGA DE SOLICITUD: Se superó el límite de limitación para una API",
        "status_500": "ERROR DEL SERVIDOR INTERNO: El servidor encontró una excepción no controlada",
        "status_503": "SERVICIO NO DISPONIBLE: El servidor no puede manejar temporalmente la Solicitud",
        "status_504": "TIEMPO DE ESPERA DE LA PUERTA DE ENTRADA: El servidor que actúa como puerta de enlace no recibió una respuesta oportuna de un servidor ascendente",
        "account_deleted": "La cuenta ha sido eliminada.",
        "account_scheduled_delete": "La cuenta ya está programada para su eliminación.",
        "cors_not_allowed": "ERROR DE CORS: No permitido por Access-Control-Allow-Origin",
        "entity_exists": "La entidad ya existe.",
        "invalid_start_date": "Por favor seleccione una fecha de inicio válida",
        "invalid_start_date_past": "La fecha de inicio no puede ser en el pasado.",
        "is_required": "Se requiere {field}.",
        "org_required": "Se requiere organización para el administrador",
        "already_exists": "{entity} ya existe",
        "one_feedback": "Sólo se permite un comentario por usuario",
        "not_enrolled_course": "No estás inscrito en este curso.",
        "not_found_top_bootcamps": "Mejores bootcamps no encontrados",
        "not_found_bootcamp": "Bootcamp no encontrado con ID de {id}",
        "not_found_course": "Curso no encontrado con id de {id}",
        "not_found_enrollment": "Inscripción no encontrada con ID de {id}",
        "not_found_feedback": "No se encontraron comentarios con el ID {id}",
        "not_found": "No hay ningún usuario con id {id}",
        "bootcamp_already_published": "El usuario con ID {id} ya publicó un bootcamp",
        "failed_upload": "Por favor sube un archivo",
        "failed_upload_avatar": "Por favor sube un avatar",
        "failed_filesize": "El tamaño del archivo no puede exceder {fileSize}",
        "failed_seed": "FALLO EN LA RECOLECCIÓN DE SEMILLAS SEMILLAS",
        "failed_destroy": "NO SE PUDIÓ DESTRUIR LA/S COLECCIÓN/es",
        "failed_delete": "FALLO AL ELIMINAR LA ENTIDAD",
        "failed_delete_account": "No se pudo eliminar tu cuenta",
        "failed_find": "NO SE PUDO ENCONTRAR LA ENTIDAD",
        "failed_create": "NO SE PUDO CREAR LA ENTIDAD",
        "failed_update": "ERROR AL ACTUALIZAR LA ENTIDAD",
        "failed_register": "NO SE PUDO REGISTRAR",
        "failed_login": "FALLÓ AL INICIAR SESIÓN",
        "failed_logout": "FALLÓ AL CERRAR SESIÓN",
        "invalid_credential": "Por favor proporcione un correo electrónico y una contraseña válidos",
        "invalid_password": "Contraseña no válida",
        "invalid_token": "Token no válido",
        "nodemailer_message": "Se produjo un error: %s",
        "not_student": "La usuario {user} no es una estudiante",
        "not_owner": "El usuario {user} no está autorizado a actualizar el curso {entity}",
        "role_not_allowed": "El rol actual {role} no está autorizado a acceder a esta ruta",
        "parse_err": "Error al analizar JSON: {error}",
        "not_instance": "No se puede crear una instancia de esta clase.",
        "session_expired": "La sesión ha expirado",
        "static_class": "Esta es una clase estática",
        "failed_email": "No se pudo enviar el correo electrónico",
        "reset_subject": "Solicitud de restablecimiento de contraseña",
        "reset_message": "Se ha realizado una solicitud para restablecer su contraseña. Si realizó esta solicitud, copie el siguiente código en el mensaje en: \n\n{resetUrl} para verificar su identidad."
      }
    },
    "schema": {
      "name": "Por favor agregue un nombre/título del bootcamp",
      "max_length_name": "El nombre no puede tener más de 50 caracteres.",
      "description": "Por favor agregue una descripción",
      "min_length_description": "La descripción no puede tener menos de 20 caracteres.",
      "max_length_description": "La descripción no puede tener más de 250 caracteres.",
      "url": "Utilice una URL válida con HTTP o HTTPS",
      "max_length_phone": "El número de teléfono no puede tener más de 20 caracteres.",
      "email": "Por favor agregue un correo electrónico válido",
      "address": "Por favor agregue una dirección",
      "duration": "Por favor agregue una duración",
      "average_rating_min": "La calificación debe ser al menos 1",
      "average_rating_max": "La puntuación no debe ser superior a 10.",
      "careers": "Por favor agregue una o más carreras",
      "course_title": "Por favor agregue un título del curso",
      "course_week": "Por favor agregue el número de semanas",
      "course_tuition": "Por favor agregue un costo de matrícula",
      "minimum_skill": "Por favor agregue una habilidad mínima",
      "feedback_title": "Por favor agregue un título a sus comentarios",
      "feedback_rating": "Por favor se requiere calificación",
      "first_name": "Por favor proporcione su nombre",
      "last_name": "Por favor proporcione su familia/apellido",
      "password": "Por favor agregue una contraseña"
    },
    "success": {
      "ok": "OK: Solicitud recuperada",
      "created": "CREADO: Solicitud creada",
      "updated": "Entidad actualizada",
      "deleted": "Entidad eliminada",
      "logout": "Usuario desconectada"
    },
    "error": {
      "bad_request": "La solicitud del cliente no es válida.",
      "unauthorized": "Debe estar autenticado para acceder a este recurso.",
      "forbidden": "No tienes permiso para acceder a este recurso.",
      "not_found": "Recurso no encontrado.",
      "route_not_found": "Ruta no encontrada: {path}",
      "validation_failed": "La validación falló.",
      "account_deleted": "La cuenta ha sido eliminada.",
      "session_expired": "La sesión ha caducado.",
      "invalid_credential": "Proporcione un correo electrónico y una contraseña válidos.",
      "already_exists": "{entity} ya existe.",
      "role_not_allowed": "El rol actual {role} no está autorizado a acceder a esta ruta.",
      "required": "Se requiere {field}."
    }
  }
} as const
