export const fr = {
  "client": {
    "account": "Compte",
    "account_updated": "Compte mis à jour",
    "active": "Active",
    "add_course": "Ajouter un cours",
    "add_bootcamp": "Ajouter un camp d'entraînement",
    "add_feedback": "Ajouter des commentaires",
    "admin": "Administratrice",
    "address": "Adresse",
    "advanced": "avancée",
    "analytics": "Analytique",
    "at_risk": "À risque",
    "avatar": "Avatar",
    "avatar_url": "URL de l'avatar",
    "back": "Dos",
    "browse_bootcamps": "Parcourir les bootcamps",
    "beginner": "débutante",
    "bootcamp": "Camp d'entraînement",
    "bootcamps": "Camps d'entraînement",
    "calendar": "Calendrier",
    "career": "Carrière",
    "create_course": "Créer un cours",
    "continue": "Continuer",
    "course": "Cours",
    "courses": "Cours",
    "create_account": "Créer un compte",
    "create_an_account": "Créer un compte",
    "description": "Description",
    "done": "Fait",
    "duration": "Durée",
    "email": "E-mail",
    "enroll": "Inscrire",
    "featured_bootcamps": "Bootcamps en vedette",
    "fetching_feedbacks": "Récupération des commentaires...",
    "feedback": "Retour",
    "feedbacks": "Commentaires",
    "firstname": "Prénom",
    "get_started": "Commencer",
    "give_rating": "Donnez votre note",
    "go_back": "Retourner",
    "invite_user": "Inviter un utilisateur",
    "intermediate": "intermédiaire",
    "in_progress": "En cours",
    "lastname": "Nom de famille",
    "league_leaders": "Dirigeants de la Ligue",
    "learners": "Apprenants",
    "loading": "Chargement",
    "location": "Emplacement",
    "location_pending": "Localisation en attente",
    "log_in": "Se connecter",
    "log_in_instead": "Connectez-vous à la place",
    "log_in_add_feedback": "Connectez-vous pour ajouter des commentaires ou une note.",
    "logging_in": "Connexion",
    "log_out": "Se déconnecter",
    "logging_out": "Déconnexion",
    "manage": "Gérer",
    "manage_platform": "Gérer la plateforme",
    "minimum_skill_": "Compétence minimale",
    "name": "Nom",
    "new_bootcamp": "Nouveau camp d'entraînement",
    "no_feedback_bootcamp": "Aucun retour pour l'instant pour ce bootcamp.",
    "no_records_yet": "Aucun enregistrement pour l'instant.",
    "not_set": "Non défini",
    "not_yet_rated": "Pas encore noté",
    "organization": "Organisation",
    "overview": "Aperçu",
    "password": "Mot de passe",
    "phone": "Téléphone",
    "progress": "Progrès",
    "program_fit": "Ajustement du programme",
    "quick_actions": "Actions rapides",
    "rating": "Notation",
    "refresh": "Rafraîchir",
    "register": "Registre",
    "remote_or_pending": "À distance ou en attente",
    "retry": "Réessayer",
    "review": "Revoir",
    "save_setting": "Enregistrer le paramètre",
    "save_bootcamp": "Enregistrer le Bootcamp",
    "scholarship_available": "Bourse disponible",
    "search_bootcamps": "Rechercher des bootcamps",
    "setting": "Paramètre",
    "sort": "Trier",
    "submitting": "Soumission",
    "target_bootcamp": "Bootcamp cible",
    "typically_starts_from": "Commence généralement à partir de",
    "title": "Titre",
    "tuition": "Frais de scolarité",
    "view": "Voir",
    "update_account": "Mettre à jour le compte",
    "user": "Utilisatrice",
    "users": "Utilisatrices",
    "username": "Nom d'utilisateur",
    "view_all": "Tout afficher",
    "view_students": "Voir les étudiants",
    "website": "Site web",
    "worldwide": "mondiale.",
    "your_courses": "Vos cours",
    "bootcamp_para": {
      "1": "Comparez les programmes, les coûts, les résultats et l'orientation des cours du catalogue du projet CodeCoach.",
      "trainer_workspace": "Espace de travail du formateur"
    },
    "filters": {
      "bootcamp": {
        "rating": "Notation",
        "averageCost": "Coût faible à élevé",
        "-averageCost": "Coût élevé à faible",
        "name": "Nom"
      }
    },
    "meta": {
      "full_stack_development": "Parcours très demandé avec une large couverture d’embauche",
      "mobile_app_development": "Idéal pour les équipes de produits et le travail de startup",
      "cloud_devops": "Compétences pratiques en matière d’infrastructure et de déploiement"
    },
    "days": {
      "mon": "Lun",
      "tue": "Mar",
      "wed": "Épouser",
      "thu": "Jeu",
      "fri": "Ven",
      "sat": "Assise",
      "sun": "Soleil"
    },
    "dashboard": {
      "across_all_courses": "dans tous les cours",
      "active_courses": "Cours actifs",
      "average_progress_day": "Progression moyenne des cours par jour.",
      "average_rating": "Note moyenne",
      "average_speed": "Vitesse moyenne",
      "browse_bootcamps": "Parcourir les bootcamps",
      "browse_courses": "Parcourir les cours",
      "catalogue_interest": "Intérêt pour le catalogue",
      "completion_rate": "Taux d'achèvement",
      "courses_active": "{course}, actif",
      "courses_completed": "Cours terminés",
      "days_row": "jours d'affilée",
      "engagement_trend_week": "Tendance d'engagement tout au long de la semaine.",
      "featured_bootcamps": "Bootcamps en vedette",
      "featured_course_title_user": "Bootcamps en vedette",
      "featured_course_description_user": "Découvrez les bootcamps les mieux notés et adaptés à votre prochain mouvement.",
      "featured_course_title_trainer": "Bootcamps populaires",
      "featured_course_description_trainer": "Découvrez ce que les apprenants choisissent dans le catalogue.",
      "keep_it_up": "Continuez comme ça",
      "last_cohort": "Dernière cohorte",
      "learner_mix": "Mélange d'apprenants",
      "learning_progress": "Progrès de l'apprentissage",
      "no_course_active": "Aucun cours actif",
      "of_target_pace": "du rythme cible",
      "out_of_max_rate": "sur 5,0",
      "opportunities": "Opportunités",
      "operational_focus": "Orientation opérationnelle",
      "platform_watchlist": "Liste de surveillance des plateformes",
      "published_now": "publié maintenant",
      "recent_feedback": "Commentaires récents",
      "recent_feedbacks": "Commentaires récents",
      "recommendation_title": "Recommandations",
      "recommendations_title_user": "Recommandations pour vous",
      "recommendation_message_user": "En fonction de vos intérêts et de vos objectifs d'apprentissage.",
      "similar_bootcamps_in_market": "{index} bootcamps similaires sur le marché",
      "study_streak": "Série d'études",
      "total_students": "Nombre total d'étudiants",
      "view_profile": "Voir le profil",
      "weekly_activity": "Activité hebdomadaire",
      "welcome_back": "Content de te revoir",
      "welcome_message_user": "Continuez votre parcours d'apprentissage et explorez de nouveaux bootcamps.",
      "welcome_message_trainer": "Gérez vos bootcamps, vos cours et suivez les progrès des étudiants.",
      "welcome_message_admin": "Surveillez la plateforme, les programmes actifs et l’état du catalogue.",
      "your_current_bootcamp": "Votre bootcamp actuel",
      "your_bootcamp": "Votre bootcamp",
      "your_bootcamps": "Vos bootcamps",
      "your_current_courses": "Vos cours actuels"
    },
    "career_options": {
      "web_development": "Développement Web",
      "mobile_development": "Développement mobile",
      "ui_ux": "UI/UX",
      "data_science": "Science des données",
      "data_security": "Sécurité des données",
      "software_engineering": "Génie logiciel",
      "full_stack_web_development": "Développement Web Full Stack",
      "dev_ops": "Opérations de développement",
      "ai": "IA",
      "machine_learning": "Apprentissage automatique",
      "cloud_computing": "Informatique en nuage",
      "cyber_security": "Cybersécurité",
      "other": "Autre"
    },
    "minimum_skill": {
      "beginner": "débutante",
      "intermediate": "intermédiaire",
      "advanced": "avancée"
    },
    "traits": {
      "housing": "Logement",
      "job_assistance": "Aide à l'emploi",
      "job_guarantee": "Garantie d'emploi",
      "gi_bill_accepted": "Facture GI acceptée"
    },
    "roles": {
      "user": "Étudiante",
      "trainer": "Entraîneuse",
      "admin": "Administratrice",
      "guest": "Invitée"
    },
    "success": {
      "bootcamp_created": "Bootcamp créé",
      "course_added": "Cours ajouté",
      "user_created": "Utilisateur créé",
      "user_deleted": "Utilisateur supprimé",
      "user_updated": "Utilisateur mis à jour",
      "user_registered": "Utilisateur enregistré",
      "user_logged_in": "Utilisateur connecté"
    },
    "error": {
      "bootcamp_required": "Créez ou ouvrez un bootcamp avant d'ajouter des cours.",
      "failed_find": "Impossible de trouver le document demandé",
      "failed_link_route": "[mainRoute] : échec de la liaison de l'itinéraire : {linker}",
      "failed_update": "Échec de la mise à jour de ce document",
      "generic": "Une erreur s'est produite lors du chargement de cette page.",
      "invalid_data_response": "Réponse de données invalide",
      "league_full": "La ligue est pleine",
      "league_sched_before_invite": "Le calendrier de la ligue doit être établi avant d'inviter",
      "membership_already_processed": "Adhésion déjà traitée",
      "max_count_per_myleague": "Max {count} équipes par ma ligue",
      "missing_or_invalid_api_version": "Version de l'API manquante ou invalide",
      "no_id": "Aucune pièce d'identité ou pièce d'identité invalide fournie",
      "not_found": "INTROUVABLE : {field} introuvable",
      "unable_load_page": "Impossible de charger cette page",
      "unable_create_account": "Impossible de créer un compte",
      "unable_create_course": "Impossible de créer un cours",
      "unable_create_bootcamp": "Impossible de créer un bootcamp",
      "unable_log_in": "Impossible de se connecter",
      "user_not_authenticated": "Utilisateur non authentifié",
      "user_not_authorized": "Utilisateur non autorisé",
      "user_not_found": "Utilisateur introuvable",
      "user_has_team": "L'utilisateur a déjà une équipe",
      "user_select_team_required": "Tous les membres doivent sélectionner une équipe avant de rédiger",
      "team_has_already_selected": "{field} a déjà été sélectionné",
      "team_already_selected": "Equipe déjà sélectionnée"
    },
    "message": {
      "draft_started": "La date de draft a déjà commencé",
      "footer": "Apprenez plus rapidement grâce à des bootcamps techniques organisés et à une formation moderne des développeurs,",
      "membership_expired": "Adhésion expirée",
      "membership_processed": "Adhésion déjà traitée",
      "newly_created_bootcamp": "Le bootcamp nouvellement créé apparaîtra ici",
      "no_courses_published_yet": "Aucun cours publié pour l'instant.",
      "owner_no_myleague": "Aucune MyLeague créée",
      "find_bootcamp": "Trouvez le bon bootcamp",
      "welcome": "Bienvenue",
      "welcome_description_student": "Continuez votre parcours d'apprentissage et explorez de nouveaux bootcamps",
      "welcome_description_trainer": "Gérez vos bootcamps, vos cours et suivez les progrès des étudiants"
    },
    "nav": {
      "dashboard": "Tableau de bord",
      "bootcamp": "Camp d'entraînement",
      "bootcamps": "Camps d'entraînement",
      "users": "Utilisatrices",
      "user": {
        "user": "utilisatrice",
        "account": "Compte",
        "manage": "Gérer",
        "setting": "Paramètre",
        "log_out": "Se déconnecter"
      },
      "footer": {
        "docs": "Documents",
        "api": "API",
        "careers": "Carrières",
        "privacy": "Confidentialité",
        "all_system_operational": "Tous les systèmes opérationnels"
      },
      "sidebar": {
        "dashboard": "Tableau de bord"
      }
    },
    "validation": {
      "default": {
        "invalid": "{field} non valide",
        "length": "La longueur de {field} ({value}) doit être comprise entre {min} et {max} caractères.",
        "min_length": "La longueur {field} ({value}) doit être d'au moins {min} caractères",
        "max_length": "La longueur de {field} ({value}) dépasse la limite de caractères",
        "required": "{field} est requis",
        "unique": "{field} existe déjà"
      },
      "max_league_allowed_user": "Limite maximale ({max}) autorisée pour les ligues détenues atteinte.",
      "password": "Le mot de passe doit comporter plus de 8 caractères avec au moins une majuscule, une minuscule, un chiffre et un symbole."
    }
  },
  "server": {
    "response": {
      "exists": "{entity} existe déjà",
      "db_saved": "le nouveau {entity} a été enregistré dans la base de données",
      "success": {
        "status_200": "OK : requête récupérée",
        "status_201": "CRÉÉ : demande créée",
        "status_204": "AUCUN CONTENU : le serveur a traité avec succès la demande mais il n'y a aucun contenu à envoyer dans la réponse.",
        "photo_uploaded": "OK : Photo téléchargée",
        "badge_uploaded": "OK : badge téléchargé",
        "avatar_uploaded": "OK : Avatar téléchargé",
        "courses_deleted": "Cours en cours de suppression de l'ID du bootcamp : {id}. Recharger la page pour voir l'effet",
        "collection_seed": "MIGRATION SIMPLEMENT RÉUSSIE",
        "collection_destroyed": "COLLECTION(s) DÉTRUITE(S)",
        "logout": "Utilisateur déconnecté",
        "updated": "Entité mise à jour",
        "deleted": "Entité supprimée",
        "deleted_account": "Votre compte a été supprimé.",
        "email_sent": "E-mail envoyé",
        "nodemailer_message": "Message envoyé : %s"
      },
      "error": {
        "status_400": "MAUVAISE DEMANDE : la demande du client est invalide",
        "status_401": "NON AUTORISÉ : la demande ne peut être accordée que si le client est authentifié",
        "status_403": "INTERDIT : les autorisations nécessaires sont requises pour accéder à la ressource demandée",
        "status_404": "INTROUVABLE : la ressource demandée est introuvable",
        "status_422": "ENTITÉ INTRATRAITABLE : les données soumises dans un formulaire sont dans un format incorrect ou il manque des champs obligatoires",
        "status_429": "DEMANDE DE SURCHARGE : limite de limitation dépassée pour une API",
        "status_500": "ERREUR INTERNE DU SERVEUR : le serveur a rencontré une exception non gérée",
        "status_503": "SERVICE INDISPONIBLE : Le serveur est temporairement incapable de traiter la demande",
        "status_504": "GATEWAY TIMEOUT : le serveur agissant comme passerelle n'a pas reçu de réponse en temps opportun d'un serveur en amont.",
        "account_deleted": "Le compte a été supprimé",
        "account_scheduled_delete": "La suppression du compte est déjà programmée.",
        "cors_not_allowed": "ERREUR CORS : non autorisé par Access-Control-Allow-Origin",
        "entity_exists": "L'entité existe déjà",
        "invalid_start_date": "Veuillez sélectionner une date de début valide",
        "invalid_start_date_past": "La date de début ne peut pas être située dans le passé",
        "is_required": "{field} est requis.",
        "org_required": "L'organisation est requise pour l'administrateur",
        "already_exists": "{entity} existe déjà",
        "one_feedback": "Un seul retour par utilisateur est autorisé",
        "not_enrolled_course": "Vous n'êtes pas inscrit à ce cours",
        "not_found_top_bootcamps": "Meilleurs bootcamps introuvables",
        "not_found_bootcamp": "Bootcamp introuvable avec l'identifiant {id}",
        "not_found_course": "Cours introuvable avec l'identifiant {id}",
        "not_found_enrollment": "Inscription introuvable avec l'identifiant {id}",
        "not_found_feedback": "Aucun commentaire trouvé avec l'identifiant {id}",
        "not_found": "Il n'y a aucun utilisateur avec l'identifiant {id}",
        "bootcamp_already_published": "L'utilisateur avec l'ID {id} a déjà publié un bootcamp",
        "failed_upload": "Veuillez télécharger un fichier",
        "failed_upload_avatar": "Veuillez télécharger un avatar",
        "failed_filesize": "La taille du fichier ne peut pas dépasser {fileSize}",
        "failed_seed": "ÉCHEC DE LA COLLECTE DE GRAINES",
        "failed_destroy": "Échec de la destruction des collections",
        "failed_delete": "ÉCHEC DE LA SUPPRESSION DE L'ENTITÉ",
        "failed_delete_account": "Échec de la suppression de votre compte",
        "failed_find": "ÉCHEC DE TROUVER L'ENTITÉ",
        "failed_create": "ÉCHEC DE LA CRÉATION DE L'ENTITÉ",
        "failed_update": "Échec de la mise à jour de l'entité",
        "failed_register": "ÉCHEC DE L'INSCRIPTION",
        "failed_login": "ÉCHEC DE LA CONNEXION",
        "failed_logout": "Échec de la déconnexion",
        "invalid_credential": "Veuillez fournir un email et un mot de passe valides",
        "invalid_password": "Mot de passe invalide",
        "invalid_token": "Jeton invalide",
        "nodemailer_message": "Une erreur s'est produite : %s",
        "not_student": "L'utilisateur {user} n'est pas un étudiant",
        "not_owner": "L'utilisateur {user} n'est pas autorisé à mettre à jour le cours {entity}.",
        "role_not_allowed": "Le rôle actuel {role} n'est pas autorisé à accéder à cet itinéraire",
        "parse_err": "Erreur lors de l'analyse de JSON : {error}",
        "not_instance": "Cette classe ne peut pas être instanciée",
        "session_expired": "La session a expiré",
        "static_class": "Ceci est une classe statique",
        "failed_email": "L'e-mail n'a pas pu être envoyé",
        "reset_subject": "Demande de réinitialisation du mot de passe",
        "reset_message": "Une demande a été faite pour réinitialiser votre mot de passe. Si vous avez fait cette demande, veuillez copier le code suivant dans l'invite : \n\n{resetUrl} pour vérifier votre identité."
      }
    },
    "schema": {
      "name": "Veuillez ajouter un nom/titre de bootcamp",
      "max_length_name": "Le nom ne peut pas contenir plus de 50 caractères",
      "description": "Veuillez ajouter une description",
      "min_length_description": "La description ne peut pas contenir moins de 20 caractères",
      "max_length_description": "La description ne peut pas contenir plus de 250 caractères",
      "url": "Veuillez utiliser une URL valide avec HTTP ou HTTPS",
      "max_length_phone": "Le numéro de téléphone ne peut pas comporter plus de 20 caractères",
      "email": "Veuillez ajouter un email valide",
      "address": "Veuillez ajouter une adresse",
      "duration": "Veuillez ajouter une durée",
      "average_rating_min": "La note doit être d'au moins 1",
      "average_rating_max": "La note ne doit pas dépasser 10",
      "careers": "Veuillez ajouter une ou plusieurs carrières",
      "course_title": "Veuillez ajouter un titre de cours",
      "course_week": "Veuillez ajouter le nombre de semaines",
      "course_tuition": "Veuillez ajouter des frais de scolarité",
      "minimum_skill": "Veuillez ajouter une compétence minimale",
      "feedback_title": "Veuillez ajouter un titre à vos commentaires",
      "feedback_rating": "S'il vous plaît, une note est requise",
      "first_name": "Veuillez indiquer votre prénom",
      "last_name": "Veuillez indiquer votre nom de famille/famille",
      "password": "Veuillez ajouter un mot de passe"
    },
    "success": {
      "ok": "OK : requête récupérée",
      "created": "CRÉÉ : demande créée",
      "updated": "Entité mise à jour",
      "deleted": "Entité supprimée",
      "logout": "Utilisateur déconnecté"
    },
    "error": {
      "bad_request": "La demande du client n'est pas valide.",
      "unauthorized": "Vous devez être authentifié pour accéder à cette ressource.",
      "forbidden": "Vous n'êtes pas autorisé à accéder à cette ressource.",
      "not_found": "Ressource introuvable.",
      "route_not_found": "Itinéraire introuvable : {path}",
      "validation_failed": "La validation a échoué.",
      "account_deleted": "Le compte a été supprimé.",
      "session_expired": "La session est expirée.",
      "invalid_credential": "Veuillez fournir un e-mail et un mot de passe valides.",
      "already_exists": "{entity} existe déjà.",
      "role_not_allowed": "Le rôle actuel {role} n'est pas autorisé à accéder à cet itinéraire.",
      "required": "{field} est requis."
    }
  }
} as const
