export const fr = {
  "client": {},
  "server": {
    "response": {
      "exists": "{entity} existe déjà",
      "db_saved": "le nouveau {entity} a été enregistré dans la base de données",
      "success": {
        "status_200": "OK : requête récupérée",
        "status_201": "CRÉÉ : demande créée",
        "status_204": "AUCUN CONTENU : le serveur a traité avec succès la demande mais il n'y a aucun contenu à envoyer dans la réponse.",
        "photo_uploaded": "OK : Photo téléchargée",
        "badge_uploaded": "OK : badge téléchargé",
        "avatar_uploaded": "OK : Avatar téléchargé",
        "courses_deleted": "Cours en cours de suppression de l'ID du bootcamp : {id}. Recharger la page pour voir l'effet",
        "collection_seed": "MIGRATION SIMPLEMENT RÉUSSIE",
        "collection_destroyed": "COLLECTION(s) DÉTRUITE(S)",
        "logout": "Utilisateur déconnecté",
        "updated": "Entité mise à jour",
        "deleted": "Entité supprimée",
        "deleted_account": "Votre compte a été supprimé.",
        "email_sent": "E-mail envoyé",
        "nodemailer_message": "Message envoyé : %s"
      },
      "error": {
        "status_400": "MAUVAISE DEMANDE : la demande du client est invalide",
        "status_401": "NON AUTORISÉ : la demande ne peut être accordée que si le client est authentifié",
        "status_403": "INTERDIT : les autorisations nécessaires sont requises pour accéder à la ressource demandée",
        "status_404": "INTROUVABLE : la ressource demandée est introuvable",
        "status_422": "ENTITÉ INTRATRAITABLE : les données soumises dans un formulaire sont dans un format incorrect ou il manque des champs obligatoires",
        "status_429": "DEMANDE DE SURCHARGE : limite de limitation dépassée pour une API",
        "status_500": "ERREUR INTERNE DU SERVEUR : le serveur a rencontré une exception non gérée",
        "status_503": "SERVICE INDISPONIBLE : Le serveur est temporairement incapable de traiter la demande",
        "status_504": "GATEWAY TIMEOUT : le serveur agissant comme passerelle n'a pas reçu de réponse en temps opportun d'un serveur en amont.",
        "account_deleted": "Le compte a été supprimé",
        "account_scheduled_delete": "La suppression du compte est déjà programmée.",
        "cors_not_allowed": "ERREUR CORS : non autorisé par Access-Control-Allow-Origin",
        "entity_exists": "L'entité existe déjà",
        "invalid_start_date": "Veuillez sélectionner une date de début valide",
        "invalid_start_date_past": "La date de début ne peut pas être située dans le passé",
        "is_required": "{field} est requis.",
        "org_required": "L'organisation est requise pour l'administrateur",
        "already_exists": "{entity} existe déjà",
        "one_feedback": "Un seul retour par utilisateur est autorisé",
        "not_enrolled_course": "Vous n'êtes pas inscrit à ce cours",
        "not_found_top_bootcamps": "Meilleurs bootcamps introuvables",
        "not_found_bootcamp": "Bootcamp introuvable avec l'identifiant {id}",
        "not_found_course": "Cours introuvable avec l'identifiant {id}",
        "not_found_enrollment": "Inscription introuvable avec l'identifiant {id}",
        "not_found_feedback": "Aucun commentaire trouvé avec l'identifiant {id}",
        "not_found": "Il n'y a aucun utilisateur avec l'identifiant {id}",
        "bootcamp_already_published": "L'utilisateur avec l'ID {id} a déjà publié un bootcamp",
        "failed_upload": "Veuillez télécharger un fichier",
        "failed_upload_avatar": "Veuillez télécharger un avatar",
        "failed_filesize": "La taille du fichier ne peut pas dépasser {fileSize}",
        "failed_seed": "ÉCHEC DE LA COLLECTE DE GRAINES",
        "failed_destroy": "Échec de la destruction des collections",
        "failed_delete": "ÉCHEC DE LA SUPPRESSION DE L'ENTITÉ",
        "failed_delete_account": "Échec de la suppression de votre compte",
        "failed_find": "ÉCHEC DE TROUVER L'ENTITÉ",
        "failed_create": "ÉCHEC DE LA CRÉATION DE L'ENTITÉ",
        "failed_update": "Échec de la mise à jour de l'entité",
        "failed_register": "ÉCHEC DE L'INSCRIPTION",
        "failed_login": "ÉCHEC DE LA CONNEXION",
        "failed_logout": "Échec de la déconnexion",
        "invalid_credential": "Veuillez fournir un email et un mot de passe valides",
        "invalid_password": "Mot de passe invalide",
        "invalid_token": "Jeton invalide",
        "nodemailer_message": "Une erreur s'est produite : %s",
        "not_student": "L'utilisateur {user} n'est pas un étudiant",
        "not_owner": "L'utilisateur {user} n'est pas autorisé à mettre à jour le cours {entity}.",
        "role_not_allowed": "Le rôle actuel {role} n'est pas autorisé à accéder à cet itinéraire",
        "parse_err": "Erreur lors de l'analyse de JSON : {error}",
        "not_instance": "Cette classe ne peut pas être instanciée",
        "session_expired": "La session a expiré",
        "static_class": "Ceci est une classe statique",
        "failed_email": "L'e-mail n'a pas pu être envoyé",
        "reset_subject": "Demande de réinitialisation du mot de passe",
        "reset_message": "Une demande a été faite pour réinitialiser votre mot de passe. Si vous avez fait cette demande, veuillez copier le code suivant dans l'invite : \n\n{resetUrl} pour vérifier votre identité."
      }
    },
    "schema": {
      "name": "Veuillez ajouter un nom/titre de bootcamp",
      "max_length_name": "Le nom ne peut pas contenir plus de 50 caractères",
      "description": "Veuillez ajouter une description",
      "min_length_description": "La description ne peut pas contenir moins de 20 caractères",
      "max_length_description": "La description ne peut pas contenir plus de 250 caractères",
      "url": "Veuillez utiliser une URL valide avec HTTP ou HTTPS",
      "max_length_phone": "Le numéro de téléphone ne peut pas comporter plus de 20 caractères",
      "email": "Veuillez ajouter un email valide",
      "address": "Veuillez ajouter une adresse",
      "duration": "Veuillez ajouter une durée",
      "average_rating_min": "La note doit être d'au moins 1",
      "average_rating_max": "La note ne doit pas dépasser 10",
      "careers": "Veuillez ajouter une ou plusieurs carrières",
      "course_title": "Veuillez ajouter un titre de cours",
      "course_week": "Veuillez ajouter le nombre de semaines",
      "course_tuition": "Veuillez ajouter des frais de scolarité",
      "minimum_skill": "Veuillez ajouter une compétence minimale",
      "feedback_title": "Veuillez ajouter un titre à vos commentaires",
      "feedback_rating": "S'il vous plaît, une note est requise",
      "first_name": "Veuillez indiquer votre prénom",
      "last_name": "Veuillez indiquer votre nom de famille/famille",
      "password": "Veuillez ajouter un mot de passe"
    },
    "success": {
      "ok": "OK : requête récupérée",
      "created": "CRÉÉ : demande créée",
      "updated": "Entité mise à jour",
      "deleted": "Entité supprimée",
      "logout": "Utilisateur déconnecté"
    },
    "error": {
      "bad_request": "La demande du client n'est pas valide.",
      "unauthorized": "Vous devez être authentifié pour accéder à cette ressource.",
      "forbidden": "Vous n'êtes pas autorisé à accéder à cette ressource.",
      "not_found": "Ressource introuvable.",
      "route_not_found": "Itinéraire introuvable : {path}",
      "validation_failed": "La validation a échoué.",
      "account_deleted": "Le compte a été supprimé.",
      "session_expired": "La session est expirée.",
      "invalid_credential": "Veuillez fournir un e-mail et un mot de passe valides.",
      "already_exists": "{entity} existe déjà.",
      "role_not_allowed": "Le rôle actuel {role} n'est pas autorisé à accéder à cet itinéraire.",
      "required": "{field} est requis."
    }
  }
} as const
