export const ja = {
  "client": {},
  "server": {
    "response": {
      "exists": "{entity} はすでに存在します",
      "db_saved": "新しい {entity} がデータベースに保存されました",
      "success": {
        "status_200": "OK: リクエストがフェッチされました",
        "status_201": "CREATED: リクエストが作成されました",
        "status_204": "コンテンツがありません: サーバーはリクエストを正常に処理しましたが、応答で送信するコンテンツがありません。",
        "photo_uploaded": "OK: 写真がアップロードされました",
        "badge_uploaded": "OK: バッジがアップロードされました",
        "avatar_uploaded": "OK: アバターがアップロードされました",
        "courses_deleted": "ブートキャンプ ID: {id} からコースが削除されます。 ページをリロードして効果を確認してください",
        "collection_seed": "モック移行が成功しました",
        "collection_destroyed": "コレクションが破壊されました",
        "logout": "ユーザーがログアウトしました",
        "updated": "エンティティが更新されました",
        "deleted": "エンティティが削除されました",
        "deleted_account": "あなたのアカウントは削除されました。",
        "email_sent": "メールを送信しました",
        "nodemailer_message": "送信されたメッセージ: %s"
      },
      "error": {
        "status_400": "BAD REQUEST: クライアント要求が無効です",
        "status_401": "UNAUTHORIZED: クライアントが認証されない限りリクエストは許可されません",
        "status_403": "禁止: 要求されたリソースにアクセスするには必要な権限が必要です",
        "status_404": "NOT FOUND: 要求されたリソースが見つかりません",
        "status_422": "処理できないエンティティ: フォームで送信されたデータの形式が間違っているか、必須フィールドが欠落しています",
        "status_429": "REQUEST OVERLOAD: API のスロットル制限を超えました",
        "status_500": "内部サーバー エラー: サーバーで未処理の例外が発生しました",
        "status_503": "サービスを利用できません: サーバーは一時的にリクエストを処理できません",
        "status_504": "ゲートウェイ タイムアウト: ゲートウェイとして機能するサーバーが、上流サーバーからタイムリーな応答を受信しませんでした",
        "account_deleted": "アカウントが削除されました",
        "account_scheduled_delete": "アカウントはすでに削除される予定です。",
        "cors_not_allowed": "CORS エラー: Access-Control-Allow-Origin では許可されていません",
        "entity_exists": "エンティティはすでに存在します",
        "invalid_start_date": "有効な開始日を選択してください",
        "invalid_start_date_past": "開始日を過去にすることはできません",
        "is_required": "{field} は必須です。",
        "org_required": "管理者には組織が必要です",
        "already_exists": "{entity} はすでに存在します",
        "one_feedback": "フィードバックはユーザーごとに 1 つだけ許可されます",
        "not_enrolled_course": "あなたはこのコースに登録していません",
        "not_found_top_bootcamps": "__MISSING__",
        "not_found_bootcamp": "ID {id} のブートキャンプが見つかりません",
        "not_found_course": "ID {id} のコースが見つかりませんでした",
        "not_found_enrollment": "ID {id} の登録が見つかりませんでした",
        "not_found_feedback": "ID {id} のフィードバックが見つかりませんでした",
        "not_found": "ID {id} のユーザーはいません",
        "bootcamp_already_published": "ID {id} のユーザーはすでにブートキャンプを公開しています",
        "failed_upload": "ファイルをアップロードしてください",
        "failed_upload_avatar": "アバターをアップロードしてください",
        "failed_filesize": "ファイル サイズは {fileSize} を超えることはできません",
        "failed_seed": "シードの収集に失敗しました",
        "failed_destroy": "コレクションの破棄に失敗しました",
        "failed_delete": "エンティティの削除に失敗しました",
        "failed_delete_account": "アカウントの削除に失敗しました",
        "failed_find": "エンティティが見つかりませんでした",
        "failed_create": "エンティティの作成に失敗しました",
        "failed_update": "エンティティの更新に失敗しました",
        "failed_register": "登録に失敗しました",
        "failed_login": "ログインに失敗しました",
        "failed_logout": "ログアウトに失敗しました",
        "invalid_credential": "有効なメールアドレスとパスワードを入力してください",
        "invalid_password": "無効なパスワード",
        "invalid_token": "無効なトークン",
        "nodemailer_message": "エラーが発生しました: %s",
        "not_student": "ユーザー {user} は学生ではありません",
        "not_owner": "ユーザー {user} にはコース {entity} を更新する権限がありません",
        "role_not_allowed": "現在のロール {role} には、このルートへのアクセスが許可されていません",
        "parse_err": "JSON 解析エラー: {error}",
        "not_instance": "このクラスはインスタンス化できません",
        "session_expired": "セッションの有効期限が切れました",
        "static_class": "これは静的クラスです",
        "failed_email": "メールを送信できませんでした",
        "reset_subject": "パスワードリセットリクエスト",
        "reset_message": "パスワードをリセットするリクエストが行われました。 このリクエストを行った場合は、次のコードをプロンプトにコピーしてください。 \n\n{resetUrl} を使用して身元を確認します。"
      }
    },
    "schema": {
      "name": "ブートキャンプの名前/タイトルを追加してください",
      "max_length_name": "名前は50文字以内にしてください",
      "description": "説明を追加してください",
      "min_length_description": "説明は 20 文字以上にする必要があります",
      "max_length_description": "説明は 250 文字以内にしてください",
      "url": "HTTP または HTTPS で有効な URL を使用してください",
      "max_length_phone": "電話番号は 20 文字以内にしてください",
      "email": "有効なメールアドレスを追加してください",
      "address": "住所を追加してください",
      "duration": "期間を追加してください",
      "average_rating_min": "__MISSING__",
      "average_rating_max": "評価は 10 を超えることはできません",
      "careers": "1 つ以上のキャリアを追加してください",
      "course_title": "コースタイトルを追加してください",
      "course_week": "週数を追加してください",
      "course_tuition": "授業料を追加してください",
      "minimum_skill": "最低限のスキルを追加してください",
      "feedback_title": "フィードバックにタイトルを追加してください",
      "feedback_rating": "評価は必須です",
      "first_name": "あなたの名を入力してください",
      "last_name": "あなたの家族/姓を入力してください",
      "password": "パスワードを追加してください"
    },
    "success": {
      "ok": "OK: リクエストがフェッチされました",
      "created": "CREATED: リクエストが作成されました",
      "updated": "エンティティが更新されました",
      "deleted": "エンティティが削除されました",
      "logout": "ユーザーがログアウトしました"
    },
    "error": {
      "bad_request": "クライアントのリクエストは無効です。",
      "unauthorized": "このリソースにアクセスするには認証が必要です。",
      "forbidden": "このリソースにアクセスする権限がありません。",
      "not_found": "リソースが見つかりません。",
      "route_not_found": "ルートが見つかりません: {path}",
      "validation_failed": "検証が失敗しました。",
      "account_deleted": "アカウントが削除されました。",
      "session_expired": "セッションの有効期限が切れました。",
      "invalid_credential": "有効な電子メールとパスワードを入力してください。",
      "already_exists": "{entity} はすでに存在します。",
      "role_not_allowed": "現在のロール {role} には、このルートへのアクセスが許可されていません。",
      "required": "{field} は必須です。"
    }
  }
} as const
