export const ja = {
  "client": {
    "account": "アカウント",
    "account_updated": "アカウントが更新されました",
    "active": "アクティブ",
    "add_course": "コースを追加",
    "add_bootcamp": "ブートキャンプを追加",
    "add_feedback": "フィードバックを追加する",
    "admin": "管理者",
    "address": "住所",
    "advanced": "高度な",
    "analytics": "分析",
    "at_risk": "危険にさらされています",
    "avatar": "アバター",
    "avatar_url": "アバターURL",
    "back": "戻る",
    "browse_bootcamps": "ブートキャンプを参照する",
    "beginner": "初心者",
    "bootcamp": "ブートキャンプ",
    "bootcamps": "ブートキャンプ",
    "calendar": "カレンダー",
    "career": "キャリア",
    "create_course": "コースの作成",
    "continue": "続く",
    "course": "コース",
    "courses": "コース",
    "create_account": "アカウントを作成する",
    "create_an_account": "アカウントを作成する",
    "description": "説明",
    "done": "終わり",
    "duration": "間隔",
    "email": "電子メール",
    "enroll": "登録する",
    "featured_bootcamps": "注目のブートキャンプ",
    "fetching_feedbacks": "フィードバックを取得中...",
    "feedback": "フィードバック",
    "feedbacks": "フィードバック",
    "firstname": "ファーストネーム",
    "get_started": "始めましょう",
    "give_rating": "あなたの評価を与えてください",
    "go_back": "戻る",
    "invite_user": "ユーザーを招待",
    "intermediate": "中級",
    "in_progress": "進行中",
    "lastname": "苗字",
    "league_leaders": "リーグリーダー",
    "learners": "学習者",
    "loading": "読み込み中",
    "location": "位置",
    "location_pending": "場所は保留中",
    "log_in": "ログイン",
    "log_in_instead": "代わりにログインしてください",
    "log_in_add_feedback": "フィードバックを追加したり評価したりするには、ログインしてください。",
    "logging_in": "ログインする",
    "log_out": "ログアウト",
    "logging_out": "ログアウトする",
    "manage": "管理",
    "manage_platform": "プラットフォームの管理",
    "minimum_skill_": "最低限のスキル",
    "name": "名前",
    "new_bootcamp": "新しいブートキャンプ",
    "no_feedback_bootcamp": "このブートキャンプに対するフィードバックはまだありません。",
    "no_records_yet": "まだ記録がありません。",
    "not_set": "未設定",
    "not_yet_rated": "まだ評価されていません",
    "organization": "組織",
    "overview": "概要",
    "password": "パスワード",
    "phone": "電話",
    "progress": "進捗",
    "program_fit": "プログラムフィット",
    "quick_actions": "クイックアクション",
    "rating": "評価",
    "refresh": "リフレッシュ",
    "register": "登録する",
    "remote_or_pending": "リモートまたはロケーションが保留中",
    "retry": "リトライ",
    "review": "レビュー",
    "save_setting": "設定の保存",
    "save_bootcamp": "ブートキャンプを保存する",
    "scholarship_available": "奨学金あり",
    "search_bootcamps": "ブートキャンプを検索する",
    "setting": "設定",
    "sort": "選別",
    "submitting": "提出中",
    "target_bootcamp": "ターゲットブートキャンプ",
    "typically_starts_from": "通常は次から始まります",
    "title": "タイトル",
    "tuition": "学費",
    "view": "ビュー",
    "update_account": "アカウントを更新する",
    "user": "ユーザー",
    "users": "ユーザー",
    "username": "ユーザー名",
    "view_all": "すべて見る",
    "view_students": "学生を見る",
    "website": "Webサイト",
    "worldwide": "世界中で。",
    "your_courses": "あなたのコース",
    "bootcamp_para": {
      "1": "CodeCoach プロジェクトのカタログからプログラム、コスト、成果、コースの焦点を比較します。",
      "trainer_workspace": "トレーナーワークスペース"
    },
    "filters": {
      "bootcamp": {
        "rating": "評価",
        "averageCost": "コストが低いものから高いものまで",
        "-averageCost": "費用が高いものから安いものまで",
        "name": "名前"
      }
    },
    "meta": {
      "full_stack_development": "幅広い採用範囲を備えた需要の高い経路",
      "mobile_app_development": "製品チームやスタートアップの仕事に最適",
      "cloud_devops": "実践的なインフラストラクチャと導入スキル"
    },
    "days": {
      "mon": "月",
      "tue": "火",
      "wed": "水",
      "thu": "木",
      "fri": "金",
      "sat": "土",
      "sun": "太陽"
    },
    "dashboard": {
      "across_all_courses": "すべてのコースにわたって",
      "active_courses": "アクティブコース",
      "average_progress_day": "日ごとのクラスの平均進捗状況。",
      "average_rating": "平均評価",
      "average_speed": "平均速度",
      "browse_bootcamps": "ブートキャンプを参照する",
      "browse_courses": "コースを参照する",
      "catalogue_interest": "カタログへの関心",
      "completion_rate": "完了率",
      "courses_active": "{course}、アクティブ",
      "courses_completed": "完了したコース",
      "days_row": "連日",
      "engagement_trend_week": "週全体のエンゲージメントの傾向。",
      "featured_bootcamps": "注目のブートキャンプ",
      "featured_course_title_user": "注目のブートキャンプ",
      "featured_course_description_user": "あなたの次のステップに合わせた最高評価のブートキャンプを見つけてください。",
      "featured_course_title_trainer": "人気のブートキャンプ",
      "featured_course_description_trainer": "学習者がカタログ全体で何を選択しているかを確認します。",
      "keep_it_up": "それを維持する",
      "last_cohort": "最終コホート",
      "learner_mix": "学習者ミックス",
      "learning_progress": "学習の進捗状況",
      "no_course_active": "アクティブなコースはありません",
      "of_target_pace": "目標ペースの",
      "out_of_max_rate": "5.0点中",
      "opportunities": "機会",
      "operational_focus": "運用上の焦点",
      "platform_watchlist": "プラットフォームウォッチリスト",
      "published_now": "現在公開中",
      "recent_feedback": "最近のフィードバック",
      "recent_feedbacks": "最近のフィードバック",
      "recommendation_title": "推奨事項",
      "recommendations_title_user": "あなたへのおすすめ",
      "recommendation_message_user": "あなたの興味と学習目標に基づいて。",
      "similar_bootcamps_in_market": "{index} 市場の同様のブートキャンプ",
      "study_streak": "連続学習",
      "total_students": "学生総数",
      "view_profile": "プロフィールを見る",
      "weekly_activity": "毎週のアクティビティ",
      "welcome_back": "おかえり",
      "welcome_message_user": "学習の旅を続けて、新しいブートキャンプを探索してください。",
      "welcome_message_trainer": "ブートキャンプ、コースを管理し、生徒の進捗状況を追跡します。",
      "welcome_message_admin": "プラットフォーム、アクティブなプログラム、カタログの健全性を監視します。",
      "your_current_bootcamp": "現在のブートキャンプ",
      "your_bootcamp": "あなたのブートキャンプ",
      "your_bootcamps": "あなたのブートキャンプ",
      "your_current_courses": "現在のコース"
    },
    "career_options": {
      "web_development": "ウェブ開発",
      "mobile_development": "モバイル開発",
      "ui_ux": "UI/UX",
      "data_science": "データサイエンス",
      "data_security": "データセキュリティ",
      "software_engineering": "ソフトウェアエンジニアリング",
      "full_stack_web_development": "フルスタック Web 開発",
      "dev_ops": "開発運用",
      "ai": "AI",
      "machine_learning": "機械学習",
      "cloud_computing": "クラウドコンピューティング",
      "cyber_security": "サイバーセキュリティ",
      "other": "他の"
    },
    "minimum_skill": {
      "beginner": "初心者",
      "intermediate": "中級",
      "advanced": "高度な"
    },
    "traits": {
      "housing": "ハウジング",
      "job_assistance": "就職支援",
      "job_guarantee": "雇用保証",
      "gi_bill_accepted": "GI 請求書が受理されました"
    },
    "roles": {
      "user": "学生",
      "trainer": "トレーナー",
      "admin": "管理者",
      "guest": "ゲスト"
    },
    "success": {
      "bootcamp_created": "ブートキャンプが作成されました",
      "course_added": "コース追加",
      "user_created": "ユーザーが作成しました",
      "user_deleted": "ユーザーが削除されました",
      "user_updated": "ユーザーが更新されました",
      "user_registered": "ユーザー登録済み",
      "user_logged_in": "ユーザーがログインしました"
    },
    "error": {
      "bootcamp_required": "コースを追加する前に、ブートキャンプを作成するか開いてください。",
      "failed_find": "要求されたドキュメントが見つかりませんでした",
      "failed_link_route": "[mainRoute]: ルートのリンクに失敗しました: {linker}",
      "failed_update": "このドキュメントを更新できませんでした",
      "generic": "このページの読み込み中に問題が発生しました。",
      "invalid_data_response": "無効なデータ応答",
      "league_full": "リーグは満員です",
      "league_sched_before_invite": "リーグのスケジュールは招待する前に設定する必要があります",
      "membership_already_processed": "メンバーシップはすでに処理されています",
      "max_count_per_myleague": "マイリーグあたり最大 {count} チーム",
      "missing_or_invalid_api_version": "API バージョンが見つからないか無効です",
      "no_id": "ID が指定されていないか無効な ID が指定されました",
      "not_found": "見つかりません: {field} が見つかりません",
      "unable_load_page": "このページを読み込めません",
      "unable_create_account": "アカウントを作成できません",
      "unable_create_course": "コースを作成できません",
      "unable_create_bootcamp": "ブートキャンプを作成できません",
      "unable_log_in": "ログインできない",
      "user_not_authenticated": "ユーザーが認証されていません",
      "user_not_authorized": "ユーザーは権限がありません",
      "user_not_found": "ユーザーが見つかりません",
      "user_has_team": "ユーザーはすでにチームを持っています",
      "user_select_team_required": "すべてのメンバーはドラフトする前にチームを選択する必要があります",
      "team_has_already_selected": "{field} はすでに選択されています",
      "team_already_selected": "チームはすでに選択されています"
    },
    "message": {
      "draft_started": "ドラフト日はすでに始まっています",
      "footer": "厳選されたテクニカル ブートキャンプと最新の開発者教育により、より迅速に学習できます。",
      "membership_expired": "メンバーシップの有効期限が切れました",
      "membership_processed": "メンバーシップはすでに処理されています",
      "newly_created_bootcamp": "新しく作成されたブートキャンプがここに表示されます",
      "no_courses_published_yet": "まだ公開されているコースはありません。",
      "owner_no_myleague": "MyLeague が作成されていません",
      "find_bootcamp": "適切なブートキャンプを見つける",
      "welcome": "いらっしゃいませ",
      "welcome_description_student": "学習の旅を続けて、新しいブートキャンプを探索してください",
      "welcome_description_trainer": "ブートキャンプ、コースを管理し、生徒の進捗状況を追跡します"
    },
    "nav": {
      "dashboard": "ダッシュボード",
      "bootcamp": "ブートキャンプ",
      "bootcamps": "ブートキャンプ",
      "users": "ユーザー",
      "user": {
        "user": "ユーザー",
        "account": "アカウント",
        "manage": "管理",
        "setting": "設定",
        "log_out": "ログアウト"
      },
      "footer": {
        "docs": "ドキュメント",
        "api": "API",
        "careers": "キャリア",
        "privacy": "プライバシー",
        "all_system_operational": "すべてのシステムが稼働中"
      },
      "sidebar": {
        "dashboard": "ダッシュボード"
      }
    },
    "validation": {
      "default": {
        "invalid": "無効な{field}",
        "length": "{field} 長さ ({value}) は {min} 文字から {max} 文字まででなければなりません",
        "min_length": "{field} 長さ ({value}) は少なくとも {min} 文字である必要があります",
        "max_length": "{field} の長さ ({value}) が文字数制限を超えています",
        "required": "{field} は必須です",
        "unique": "{field} はすでに存在します"
      },
      "max_league_allowed_user": "所有するリーグに許可される最大制限 ({max}) に達しました",
      "password": "パスワードは、少なくとも 1 つの大文字、小文字、数字、記号を含む 8 文字以上である必要があります。"
    }
  },
  "server": {
    "response": {
      "exists": "{entity} はすでに存在します",
      "db_saved": "新しい {entity} がデータベースに保存されました",
      "success": {
        "status_200": "OK: リクエストがフェッチされました",
        "status_201": "CREATED: リクエストが作成されました",
        "status_204": "コンテンツがありません: サーバーはリクエストを正常に処理しましたが、応答で送信するコンテンツがありません。",
        "photo_uploaded": "OK: 写真がアップロードされました",
        "badge_uploaded": "OK: バッジがアップロードされました",
        "avatar_uploaded": "OK: アバターがアップロードされました",
        "courses_deleted": "ブートキャンプ ID: {id} からコースが削除されます。 ページをリロードして効果を確認してください",
        "collection_seed": "モック移行が成功しました",
        "collection_destroyed": "コレクションが破壊されました",
        "logout": "ユーザーがログアウトしました",
        "updated": "エンティティが更新されました",
        "deleted": "エンティティが削除されました",
        "deleted_account": "あなたのアカウントは削除されました。",
        "email_sent": "メールを送信しました",
        "nodemailer_message": "送信されたメッセージ: %s"
      },
      "error": {
        "status_400": "BAD REQUEST: クライアント要求が無効です",
        "status_401": "UNAUTHORIZED: クライアントが認証されない限りリクエストは許可されません",
        "status_403": "禁止: 要求されたリソースにアクセスするには必要な権限が必要です",
        "status_404": "NOT FOUND: 要求されたリソースが見つかりません",
        "status_422": "処理できないエンティティ: フォームで送信されたデータの形式が間違っているか、必須フィールドが欠落しています",
        "status_429": "REQUEST OVERLOAD: API のスロットル制限を超えました",
        "status_500": "内部サーバー エラー: サーバーで未処理の例外が発生しました",
        "status_503": "サービスを利用できません: サーバーは一時的にリクエストを処理できません",
        "status_504": "ゲートウェイ タイムアウト: ゲートウェイとして機能するサーバーが、上流サーバーからタイムリーな応答を受信しませんでした",
        "account_deleted": "アカウントが削除されました",
        "account_scheduled_delete": "アカウントはすでに削除される予定です。",
        "cors_not_allowed": "CORS エラー: Access-Control-Allow-Origin では許可されていません",
        "entity_exists": "エンティティはすでに存在します",
        "invalid_start_date": "有効な開始日を選択してください",
        "invalid_start_date_past": "開始日を過去にすることはできません",
        "is_required": "{field} は必須です。",
        "org_required": "管理者には組織が必要です",
        "already_exists": "{entity} はすでに存在します",
        "one_feedback": "フィードバックはユーザーごとに 1 つだけ許可されます",
        "not_enrolled_course": "あなたはこのコースに登録していません",
        "not_found_top_bootcamps": "トップのブートキャンプが見つかりません",
        "not_found_bootcamp": "ID {id} のブートキャンプが見つかりません",
        "not_found_course": "ID {id} のコースが見つかりませんでした",
        "not_found_enrollment": "ID {id} の登録が見つかりませんでした",
        "not_found_feedback": "ID {id} のフィードバックが見つかりませんでした",
        "not_found": "ID {id} のユーザーはいません",
        "bootcamp_already_published": "ID {id} のユーザーはすでにブートキャンプを公開しています",
        "failed_upload": "ファイルをアップロードしてください",
        "failed_upload_avatar": "アバターをアップロードしてください",
        "failed_filesize": "ファイル サイズは {fileSize} を超えることはできません",
        "failed_seed": "シードの収集に失敗しました",
        "failed_destroy": "コレクションの破棄に失敗しました",
        "failed_delete": "エンティティの削除に失敗しました",
        "failed_delete_account": "アカウントの削除に失敗しました",
        "failed_find": "エンティティが見つかりませんでした",
        "failed_create": "エンティティの作成に失敗しました",
        "failed_update": "エンティティの更新に失敗しました",
        "failed_register": "登録に失敗しました",
        "failed_login": "ログインに失敗しました",
        "failed_logout": "ログアウトに失敗しました",
        "invalid_credential": "有効なメールアドレスとパスワードを入力してください",
        "invalid_password": "無効なパスワード",
        "invalid_token": "無効なトークン",
        "nodemailer_message": "エラーが発生しました: %s",
        "not_student": "ユーザー {user} は学生ではありません",
        "not_owner": "ユーザー {user} にはコース {entity} を更新する権限がありません",
        "role_not_allowed": "現在のロール {role} には、このルートへのアクセスが許可されていません",
        "parse_err": "JSON 解析エラー: {error}",
        "not_instance": "このクラスはインスタンス化できません",
        "session_expired": "セッションの有効期限が切れました",
        "static_class": "これは静的クラスです",
        "failed_email": "メールを送信できませんでした",
        "reset_subject": "パスワードリセットリクエスト",
        "reset_message": "パスワードをリセットするリクエストが行われました。 このリクエストを行った場合は、次のコードをプロンプトにコピーしてください。 \n\n{resetUrl} を使用して身元を確認します。"
      }
    },
    "schema": {
      "name": "ブートキャンプの名前/タイトルを追加してください",
      "max_length_name": "名前は50文字以内にしてください",
      "description": "説明を追加してください",
      "min_length_description": "説明は 20 文字以上にする必要があります",
      "max_length_description": "説明は 250 文字以内にしてください",
      "url": "HTTP または HTTPS で有効な URL を使用してください",
      "max_length_phone": "電話番号は 20 文字以内にしてください",
      "email": "有効なメールアドレスを追加してください",
      "address": "住所を追加してください",
      "duration": "期間を追加してください",
      "average_rating_min": "評価は少なくとも 1 である必要があります",
      "average_rating_max": "評価は 10 を超えることはできません",
      "careers": "1 つ以上のキャリアを追加してください",
      "course_title": "コースタイトルを追加してください",
      "course_week": "週数を追加してください",
      "course_tuition": "授業料を追加してください",
      "minimum_skill": "最低限のスキルを追加してください",
      "feedback_title": "フィードバックにタイトルを追加してください",
      "feedback_rating": "評価は必須です",
      "first_name": "あなたの名を入力してください",
      "last_name": "あなたの家族/姓を入力してください",
      "password": "パスワードを追加してください"
    },
    "success": {
      "ok": "OK: リクエストがフェッチされました",
      "created": "CREATED: リクエストが作成されました",
      "updated": "エンティティが更新されました",
      "deleted": "エンティティが削除されました",
      "logout": "ユーザーがログアウトしました"
    },
    "error": {
      "bad_request": "クライアントのリクエストは無効です。",
      "unauthorized": "このリソースにアクセスするには認証が必要です。",
      "forbidden": "このリソースにアクセスする権限がありません。",
      "not_found": "リソースが見つかりません。",
      "route_not_found": "ルートが見つかりません: {path}",
      "validation_failed": "検証が失敗しました。",
      "account_deleted": "アカウントが削除されました。",
      "session_expired": "セッションの有効期限が切れました。",
      "invalid_credential": "有効な電子メールとパスワードを入力してください。",
      "already_exists": "{entity} はすでに存在します。",
      "role_not_allowed": "現在のロール {role} には、このルートへのアクセスが許可されていません。",
      "required": "{field} は必須です。"
    }
  }
} as const
